USE DIGITAL_JSP;

CREATE TABLE IF NOT EXISTS board(
	num INT PRIMARY KEY AUTO_INCREMENT ,
	title VARCHAR(20) NOT NULL ,
	name VARCHAR(20) NOT NULL ,
	password VARCHAR(30) NOT NULL ,
	message VARCHAR(100) ,
	writeDate DATETIME NOT NULL
);

SELECT * FROM board;