USE digital_jsp;

CREATE TABLE If NOT EXISTS tbl_member(
	num INT(8) PRIMARY KEY AUTO_INCREMENT,
	id VARCHAR(300) UNIQUE NOT NULL,
	pass VARCHAR(200)NOT NULL,
	name VARCHAR(30) NOT NULL,
	addr VARCHAR(300),
	phone VARCHAR(300) NOT NULL
);


SELECT * FROM tbl_member;